"""empty message

Revision ID: 1f2cbe4fed00
Revises: 98face93113c
Create Date: 2026-01-19 15:41:30.764780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f2cbe4fed00'
down_revision = '98face93113c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terrain', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('resources', sa.String(length=10), nullable=True))
        batch_op.drop_column('terreno')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terreno', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.drop_column('resources')
        batch_op.drop_column('terrain')

    # ### end Alembic commands ###
